# config.py


SD_CARD_PATH = "/home/pi/ARCRover/SDCard"


GAMEPAD_AXIS_LEFT_Y = 'ABS_Y'
GAMEPAD_AXIS_RIGHT_X = 'ABS_RX'
GAMEPAD_BUTTON_A = 'BTN_SOUTH'  
GAMEPAD_BUTTON_B = 'BTN_EAST'  
GAMEPAD_BUTTON_X = 'BTN_WEST'   
GAMEPAD_BUTTON_Y = 'BTN_NORTH'    
GAMEPAD_BUTTON_PHOTO = GAMEPAD_BUTTON_X  
GAMEPAD_BUTTON_LOG_DATA = GAMEPAD_BUTTON_A 
GAMEPAD_DEADZONE = 0.1


MOTOR_LEFT_FRONT_FORWARD = 17 #IN1 forward
MOTOR_LEFT_FRONT_BACKWARD = 27 #IN2 backward
MOTOR_LEFT_FRONT_ENABLE = 16  #ENA speed

MOTOR_LEFT_REAR_FORWARD = 22 #IN3 forward
MOTOR_LEFT_REAR_BACKWARD = 5 #IN4 backward
MOTOR_LEFT_REAR_ENABLE = 19 #ENB speed


MOTOR_RIGHT_FRONT_FORWARD = 23 #IN1 forward
MOTOR_RIGHT_FRONT_BACKWARD = 24 #IN2 backward
MOTOR_RIGHT_FRONT_ENABLE = 20 #ENA speed

MOTOR_RIGHT_REAR_FORWARD = 6 #IN3 forward
MOTOR_RIGHT_REAR_BACKWARD = 13 #IN4 backward
MOTOR_RIGHT_REAR_ENABLE = 21 #ENB speed


CAMERA_SERVO_PIN = 25 
ARM_SERVO_PIN = 12    

#IMU stabilizasyon değerleri, değişebilir
STABILIZE_KP = 0.8  # Proportional gain
STABILIZE_KI = 0.2  # Integral gain

# DHT11 
DHT11_PIN = 4 

# MCP3008
SOIL_SENSOR_ADC_CHANNEL = 0

#adc değerini test edip belirle
SOIL_MOISTURE_DRY_VALUE = 800  #kuruyken
SOIL_MOISTURE_WET_VALUE = 400  #sudayken


#GPS
GPS_SERIAL_PORT = '/dev/serial0'
GPS_BAUD_RATE = 9600