# config.py


SD_CARD_PATH = "/home/pi/ARCRover/SDCard"


GAMEPAD_AXIS_LEFT_Y = 'ABS_Y'
GAMEPAD_AXIS_RIGHT_X = 'ABS_RX'
GAMEPAD_BUTTON_A = 'BTN_SOUTH'  
GAMEPAD_BUTTON_B = 'BTN_EAST'  
GAMEPAD_BUTTON_X = 'BTN_WEST'   
GAMEPAD_BUTTON_Y = 'BTN_NORTH'    
GAMEPAD_BUTTON_PHOTO = GAMEPAD_BUTTON_X  
GAMEPAD_BUTTON_LOG_DATA = GAMEPAD_BUTTON_A 


MOTOR_LEFT_FORWARD = 17  
MOTOR_LEFT_BACKWARD = 27 
MOTOR_RIGHT_FORWARD = 23 
MOTOR_RIGHT_BACKWARD = 24


CAMERA_SERVO_PIN = 25 
ARM_SERVO_PIN = 12    


# DHT11 
DHT11_PIN = 4 

# MCP3008
SOIL_SENSOR_ADC_CHANNEL = 0

#adc değerini test edip belirle
SOIL_MOISTURE_DRY_VALUE = 800  #kuruyken
SOIL_MOISTURE_WET_VALUE = 400  #sudayken


#GPS
GPS_SERIAL_PORT = '/dev/serial0'
GPS_BAUD_RATE = 9600